
services:
  - type: web
    name: assignmate-backend
    runtime: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: assignmate-frontend
    runtime: node
    plan: free
    region: oregon
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production